### ISSUE TITLE
TypeError: list indices must be integers or slices, not list

### ISSUE THREAD

**Issue by SeekPoint** [shiningliang/CCKS2019-IPRE#2]
ub16c9@ub16c9-gpu:~/ub16_prj/CCKS2019-IPRE$ python3.6 baseline.py --level sent 
build model
2019-06-02 22:58:55.294153: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-02 22:58:55.417652: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-02 22:58:55.418117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.02GiB
2019-06-02 22:58:55.418134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2019-06-02 22:58:55.631908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-02 22:58:55.631943: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2019-06-02 22:58:55.631952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2019-06-02 22:58:55.632151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9694 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Loading train sets
Num of samples - 287351
Loading dev sets
Num of samples - 38417
Epoch - 1
idx is [108382, 104069, 92363, 55506, 25797, 198356, 45966, 278102, 44711, 6441, 98484, 91031, 247481, 107862, 150600, 210360, 251009, 275757, 93113, 178229, 181431, 75470, 247811, 284634, 55846, 197823, 33395, 116269, 156464, 172315, 175953, 145382, 36583, 206236, 36568, 185428, 74723, 190735, 214043, 170463, 27138, 26131, 221118, 203571, 42438, 215494, 265856, 209666, 11324, 183038, 262560, 65749, 133393, 92817, 44109, 222598, 37094, 19569, 214906, 24742, 257085, 273134, 68506, 193807]
Traceback (most recent call last):
  File "baseline.py", line 434, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "baseline.py", line 430, in main
    model.run_model(sess, saver)
  File "baseline.py", line 356, in run_model
    for batch in train_batchers:
  File "baseline.py", line 172, in data_batcher
    yield all_sents[idx], all_labels[idx], None
TypeError: list indices must be integers or slices, not list
ub16c9@ub16c9-gpu:~/ub16_prj/CCKS2019-IPRE$

**Comment by lzx8062456** [comment]
请问大佬如何解决的？
